export const TEXT = {
    APP_NAME: "Kao pickleball",
    MENU: "Menu",
    USERNAME: "Username",
    PASSWORD: "Password",
    LOGIN: "Đăng nhập",
    LOGIN_FAILED: "Username hoặc password không đúng",
    FIELD_REQUIRED: "Field này bắt buộc",
    MATCH: "Trận đấu",
    PLAYER: "Người chơi",
    CHECK_IN: "Check-in",
    CHECK_OUT: "Check-out",
    START: "Bắt đầu",
    NAME: "Tên",
    GENDER: "Giới tính",
    LEVEL: "Level",
    EDIT: "Cập nhập",
    DELETE: "Xóa",
};
