export const TEXT = {
    APP_NAME: "Kao pickleball",
    MENU: "Menu",
    USERNAME: "Username",
    PASSWORD: "Password",
    LOGIN: "Đăng nhập",
    LOGIN_FAILED: "Username hoặc password không đúng",
    FIELD_REQUIRED: "Field này bắt buộc",
    MATCH: "Trận đấu",
    PLAYER: "Người chơi",
    CHECK_IN: "Check-in",
    CHECK_OUT: "Check-out",
    START: "Bắt đầu",
    NAME: "Tên",
    PHONE: "Số điện thoại",
    GENDER: "Giới tính",
    LEVEL: "Level",
    ADD: "Thêm",
    UPDATE: "Cập nhập",
    DELETE: "Xóa",
    CONFIRM_DELETE: "Bạn có chắc chắn muốn xóa",
    SUBMIT: "Xác nhận",
    SUCCESSFULLY: "Thành công",
    CANCEL: "Hủy",
};
