import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import MainLayout from "@/layouts";
import Provider from "@/components/Provider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // getServerSession
    const session = await auth();

    const renderLayout = () => {
        if (session) {
            return (
                <Provider session={session}>
                    <MainLayout session={session}>{children}</MainLayout>
                </Provider>
            );
        }

        return children;
    };

    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">{renderLayout()}</body>
        </html>
    );
}
